# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rj-paper.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(corVis)
library(palmerpenguins)
library(ggplot2)
library(dplyr)
library(kableExtra)
library(magrittr)


## ----corrdisplay-packages,warning=FALSE,message=FALSE,echo=FALSE--------------
library(kableExtra)

Package <- c("corrplot","corrr","corrgrapher","linkspotter",  "correlation","corVis")

Display <- c("heatmap","heatmap/network","network","network","heatmap/network","heatmap/matrix/linear")


MixedVariables <- c(" "," "," ","Yes"," ","Yes")



df <- data.frame(Package=Package,
                 Display=Display,
                 MixedVariables=MixedVariables)

kableExtra::kbl(df, booktabs = T, caption = "List of the R packages dealing with correlation or correlation displays with information on whether the plots display multiple measures, conditional display of measures and mixed variables in a single plot")
#print(table_1)
#df %>%
  #kbl() %>%
  #kable_styling(bootstrap_options = "striped", full_width = F, position = "left")


## ----function-corVis,warning=FALSE,message=FALSE,echo=FALSE-------------------
library(kableExtra)

Function <- c("calc_assoc","calc_assoc_all","plot_assoc_matrix","plot_assoc_linear",
              "show_assoc")

Usage <- c("Calculation","Calculation","Visualization","Visualization",
           "Visualization")

#Usage <- c(rep("Calculation",5),rep("Visualization",3),rep("Visualization",5),rep("Visualization",4),rep("Visualization",5))

Description <- c("Calculates association measures",
                 
                 "Calculates all the association measures available in package",
                 
                 "Visualize assocition and conditional association in matrix plot",
                 
                 "Visualize assocition and conditional association in linear plot",
                 
                 "Association (or conditional) plot for a pair of variables")


df <- data.frame(Function=Function,
                 Usage=Usage,
                 Description=Description)

kableExtra::kbl(df,booktabs = T, caption = "List of functions in corVis package") %>%
  kableExtra::column_spec(1, bold=T)


  #kableExtra::collapse_rows(columns = 1:2)

#print(table_1)
#df %>%
  #kbl() %>%
  #kable_styling(bootstrap_options = "striped", full_width = F, position = "left")


## ----bikedata,warning=FALSE,message=FALSE,echo=FALSE--------------------------
library(kableExtra)
library(timetk)
bike <- bike_sharing_daily[,-1] |>
  mutate(season= recode_factor(season,
                               `1`="Winter", `2`="Spring", `3`="Summer", `4`="Fall"),
         weathersit= recode_factor(weathersit, 
                         `1`="clear", `2`="cloudy", `3`="lightP", `4`="heavyP"),
         holiday=recode_factor(holiday, `0` = "No", `1`="Yes"),
         workingday = recode_factor(workingday, `0` = "No", `1`="Yes"),
         yr = recode_factor(yr,`0` = 2011, `1`=2012),
         weekday = recode_factor(weekday,`0` = "sun", `1` = "mon", `2`="tue", `3` = "wed", `4`="thu", `5`="fri", `6`="sat"),
         mnth = factor(month.abb[mnth], levels=month.abb)
         )
levels(bike$weathersit)<- rev(levels(bike$weathersit))

variable <- names(bike)

description <- c("date",
                 "season with categories Winter, Spring, Summer and Fall",
                 "year of day with categories 2011 and 2012",
                 "month of day with months as categories",
                 "whether day is a holiday or not",
                 "day of the week",
                 "if day is neither weekend nor holiday it is Yes, otherwise is No",
                 "weather situation of the day with categories clear, cloudy, lightP",
                 "normalized temperature in Celsius",
                 "normalized feeling temperature in Celsius",
                 "normalized humidity",
                 "normalized windspeed",
                 "count of casual users",
                 "count of registered users",
                 "count of total rental bikes including both casual and registered")

variable_type <- c("date","nominal","nominal","nominal","nominal","nominal","nominal","nominal","numeric","numeric","numeric","numeric","numeric","numeric","numeric")

df <- data.frame(Variable=variable,
                 Description=description,
                 VariableType=variable_type
                 )

kableExtra::kbl(df, booktabs = T, caption = "Variable description of the Daily Bike Sharing dataset") |>
  kableExtra::kable_styling(latex_options = "scale_down")
#print(table_1)
#df %>%
  #kbl() %>%
  #kable_styling(bootstrap_options = "striped", full_width = F, position = "left")


## ---- pairwise-example,echo=TRUE----------------------------------------------
# a subset of bike dataset
bike_s <- bike |> 
  dplyr::select(temp, windspeed, registered,weathersit, workingday)
dcor_bike <- tbl_dcor(bike_s)
dcor_bike
class(dcor_bike)


## ----multipairwise-example,echo=TRUE------------------------------------------
multi_bike <- calc_assoc_all(bike_s,
                                 c("pearson","nmi","ace","uncertainty"))
class(multi_bike)

# calculating range of measures
multi_bike |> 
  group_by(x,y) |>
  summarise(range=max(measure)-min(measure),.groups = "drop") |>
  arrange(desc(range))


## ----condpairwise-example,echo=TRUE-------------------------------------------
cond_bike <- calc_assoc(bike_s,
                            by="weathersit")
class(cond_bike)

# calculating difference in the group
cond_bike |> 
  group_by(x,y) |>
  summarise(diff=max(measure)-min(measure),.groups = "drop") |>
  arrange(desc(diff))



## ----association-measures,echo=FALSE------------------------------------------
measures <- dplyr::tribble(
  ~name, ~nn, ~ff, ~oo, ~nf, ~from, ~range,
  "tbl_cor", "y", " ", " " ," ", "stats::cor", "[-1,1]",
  "tbl_dcor", "y", " ", " ", " ", "energy::dcor2d", "[0,1]",
  "tbl_mine", "y", " ", " ", " ", "minerva::mine", "[0,1]",
  "tbl_ace", "y", "y", " ", "y", "corVis", "[0,1]",
  "tbl_cancor", "y", "y", " ","y", "corVis", "[0,1]",
  "tbl_nmi",  "y", "y", " ", "y", "linkspotter::maxNMI", "[0,1]",
  "tbl_polycor", " ", " ","y", " ", "polycor::polychor", "[-1,1]",
  "tbl_tau", " ", " ","y", " ", "DescTools::KendalTauA,B,C,W", "[-1,1]",
  "tbl_gkGamma", " ", " ", "y", " ", "DescTools::GoodmanKruskalGamma", "[-1,1]",
  "tbl_gkTau", " ", " ", "y", " ", "DescTools::GoodmanKruskalTau", "[0,1]",
  "tbl_uncertainty", " ",  "y", " ", " ", "DescTools::UncertCoef", "[0,1]",
  "tbl_chi", " ",  "y", " ", " ", "DescTools::ContCoef", "[0,1]"
)

kableExtra::kbl(measures,booktabs = T,caption = "List of the functions available in the package for calculating different association measures along with the packages used for calculation.") %>% kableExtra::kable_styling(latex_options = "scale_down")


## ---- calc_assoc1,echo=TRUE---------------------------------------------------
bike_s <- bike |> 
  dplyr::select(temp, windspeed, registered,weathersit, workingday)
bike_s_assoc <- calc_assoc(d = bike_s,
                           by = NULL,
                           types = default_assoc(),
                           include.overall = NULL,
                           handle.na = TRUE,
                           coerce_types = NULL)
bike_s_assoc


## ---- default_assoc,echo=TRUE-------------------------------------------------
default_measures <- default_assoc()
default_measures


## ---- update_assoc,echo=TRUE--------------------------------------------------
updated_assoc <- update_assoc(default_measures,
                              num_pair = "tbl_cor",
                              num_pair_argList = "spearman",
                              mixed_pair = "tbl_ace",
                              factor_pair = "tbl_nmi")
updated_assoc
updated_bike_s_assoc <- calc_assoc(d = bike_s, 
                                 types = updated_assoc)
updated_bike_s_assoc



## ---- coerce_types, echo=TRUE-------------------------------------------------
bike_s_assoc <- calc_assoc(d = bike_s,
                           by = NULL,
                           types = default_assoc(),
                           include.overall = NULL,
                           handle.na = TRUE,
                           coerce_types = list(ordinal=c("workingday", "weathersit")))
bike_s_assoc


## ---- by,echo=TRUE------------------------------------------------------------
bike_s_assoc_by <- calc_assoc(d = bike_s,
                            by = "workingday",
                            include.overall = TRUE)
bike_s_assoc_by


## ---- include.overall,echo=TRUE-----------------------------------------------
bike_s_assoc_by <- calc_assoc(d = bike_s,
                            by = "workingday",
                            include.overall = FALSE)
bike_s_assoc_by


## -----------------------------------------------------------------------------
bike_s_assoc_multi <- calc_assoc_all(d = bike_s,
                                   measures = c("pearson",
                                                "dcor",
                                                "cancor"))
bike_s_assoc_multi


## ----assoc-matrix-bike,fig.width=3, fig.height=3, fig.align='center', fig.cap="Left: variables in default order of the data; Right: variables ordered by LPL cost function. Association measures displays for bike sharing data showing Pearson's correlation for the numeric pairs, Goodman Kruskal's gamma measure for ordered pairs and canonical correlation for factor pairs and mixed pairs. The off diagonal cells show the measure value for a variable pair using a circle glyph. The color of every circle is mapped with the measure value for the pair and the radius of the circle is mapped to absolute measure value for the corresponding variable pair. It is easier to identify pairs on the right-hand plot with strong association, for example (casual, temp), (registered,yr) and (weathersit,hum). Also, there is a negative association for (windspeed,registered) suggesting the number of registered users decreased during windy days.",echo=TRUE----

bike$dteday <- NULL 
bike$weekday <- NULL
bike$atemp <- NULL
bike$cnt <- NULL

bike_assoc <- calc_assoc(d = bike)
plot_assoc_matrix(lassoc = bike_assoc,var_order = names(bike)) #default ordering
plot_assoc_matrix(lassoc = bike_assoc, var_order = "default") # DendSer ordering


## ----coerce-types-display, fig.width=3, fig.height=3, fig.align='center', fig.cap="Association matrix display for bike sharing data showing Pearson's correlation for the numeric pairs, Goodman Kruskal's gamma measure for ordered pairs, canonical correlation for factor pairs and mixed pairs. The color of every circle is mapped with the measure value for the pair and the area of the circle is mapped by absolute measure value for the corresponding variable pair. The variables workingday, yr, weathersit and holiday have been converted to ordinals. The plot shows a strong negative association for (workingday, holiday) because no holiday is a working day.",echo=TRUE----
bike_assoc_o <- calc_assoc(bike, 
                           coerce_types=list(ordinal=c("workingday", 
                                                       "yr", 
                                                       "weathersit", 
                                                       "holiday")))

plot_assoc_matrix(bike_assoc_o,
                  glyph="circle")


## ----int-pairs-bike, fig.show="hold", out.width="50%", fig.cap = "Scatterplots for numeric pair (temp,registered) and (windspeed,hum),  boxplot for mixed pair (workingday,casual) and barplot for ordinal pair ((workingday, holiday) showing association between the pairs of variables.", echo=FALSE----
show_assoc(d = bike, 
           x = "temp", 
           y = "registered")

show_assoc(d = bike, 
           x = "windspeed", 
           y = "hum")

show_assoc(d = bike, 
           x = "workingday", 
           y = "casual")

show_assoc(d = bike, 
           x = "workingday", 
           y = "holiday")


## ----compare-matrix,fig.width=4, fig.height=4.5, fig.align='center',fig.cap="Seriated multiple association measures plot in a matrix layout for numeric variables in bike sharing data. The lollipops in each cell represent the value of the association measure colored by the type of measure. The variable pairs are ordered by the maximum value of association measures such that cells with highest value for any measure are close to the diagonal. The plot shows that pairs (casual,mnth) and (mnth,temp) might have a non-linear association which can be explored further.",echo=TRUE----
biken <- bike |>
  mutate(mnth=as.numeric(mnth)) |>
  select(where(is.numeric))

biken_assoc_all <-calc_assoc_all(biken)
plot_assoc_matrix(biken_assoc_all) 


## ----int-pairs-multiple, fig.show="hold", out.width="50%", fig.cap = "Scatterplot for variable pairs (from left to right) (casual,mnth) and (mnth,temp) showing a non-linear relationship for these pairs.",echo=FALSE----

show_assoc(biken, "mnth", "casual")
show_assoc(biken, "mnth", "temp")


## ----cond-assoc,fig.width=4.5, fig.height=4.5, fig.align='center', fig.cap="Seriated conditional association measures plot for bike sharing data showing Pearson's correlation for numeric pairs, Goodman and Kruskal's gamma for ordinal pair, canonical correlation for factor or mixed pairs. The lollipops in each cell represent the value for asssociation measure colored by the conditioning variable season. The pink horizontal line in each cell represents overall value of the association measure. The plot shows evident difference in measure value for pairs (temp, hum), (temp, registered), (temp, casual) and (registered, casual) for different seasons.",echo=TRUE----

bike_by_assoc <- select(bike, -workingday, -holiday, -mnth, -yr) |>
  calc_assoc(by="season", 
                  coerce_types=list(ordinal=c( "weathersit")))


plot_assoc_matrix(bike_by_assoc)


## ----int-pairs-conditional, fig.show="hold", out.width="50%", fig.cap = "Scatterplots for variable pairs (temp, hum), (temp, registered), (temp, casual) and (registered, casual) faceted by conditioning variable season", echo=FALSE----

show_assoc(bike, "temp", "hum", by="season")

show_assoc(bike, "temp", "registered", by="season")

show_assoc(bike, "temp", "casual", by="season")

show_assoc(bike, "registered", "casual", by="season")


## ----linear-cond-assoc,fig.width=5, fig.height=4, fig.align='left', fig.cap="Conditional association measures plot for bike sharing data in linear layout.The display has variable pairs on the Y-axis and the value of association measures on the X-axis. The points corresponding to every variable pair represents the value of association measure for different levels of the conditioning variable and the overall value of association measure.",echo=TRUE----

bike_by_assoc <- select(bike, -workingday, -holiday, -mnth, -yr) |>
  calc_assoc(by="season", 
             coerce_types=list(ordinal=c( "weathersit")),
             include.overall = F)

bike_by_assoc |> 
  group_by(x,y) |> 
  summarise(range=max(measure,na.rm = T)-min(measure,na.rm = T)) |> 
  arrange(desc(range)) -> bike_by_assoc_rng
bike_by_assoc_rngf <- filter(bike_by_assoc_rng,range>=0.25) # filtering variable pairs with a range of 0.25 or greater
bike_by_assoc_mod <- filter(bike_by_assoc,
                          x %in% bike_by_assoc_rngf$x & y %in% bike_by_assoc_rngf$y)
plot_assoc_linear(bike_by_assoc_mod, 
                  plot_type = "dotplot",
                  pair_order = "max-min",
                  limits = c(-0.5,1))


